import json
import os
import sys
import threading
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

from backend.services.config import load_config
from backend.services.telegram_digest import run_digest_job
from backend.services.telegram_files import run_files_job
from backend.services.email_sender import send_email

scheduler = BackgroundScheduler()
_jobs: dict = {}
_lock = threading.Lock()

if getattr(sys, "frozen", False):
    DATA_DIR = os.path.join(os.path.dirname(sys.executable), "data")
else:
    DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data")
HISTORY_FILE = os.path.join(DATA_DIR, "cron_history.json")
EMAIL_BODIES_DIR = os.path.join(DATA_DIR, "email_bodies")


def _ensure_dirs():
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(EMAIL_BODIES_DIR, exist_ok=True)


def _load_history() -> dict:
    if not os.path.exists(HISTORY_FILE):
        return {}
    try:
        with open(HISTORY_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def _save_history(history: dict):
    for job_id in history:
        if len(history[job_id]) > 200:
            history[job_id] = history[job_id][-200:]
    with open(HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)


def _run_job(job_id: str, func, config: dict):
    try:
        result = func(config)
    except Exception as e:
        result = {"error": str(e)}
    with _lock:
        _jobs[job_id]["total_runs"] += 1
        _jobs[job_id]["last_run"] = datetime.now().isoformat()
        _jobs[job_id]["last_result"] = result
    history = _load_history()
    if job_id not in history:
        history[job_id] = []
    history[job_id].append({"timestamp": datetime.now().isoformat(), "result": result})
    if len(history[job_id]) > 200:
        history[job_id] = history[job_id][-200:]
    _save_history(history)


def run_weekly_digest(config: dict) -> dict:
    try:
        from datetime import timedelta
        cutoff = datetime.now() - timedelta(days=7)
        entries_html = ""
        count = 0
        old_files = []
        for filename in os.listdir(EMAIL_BODIES_DIR):
            filepath = os.path.join(EMAIL_BODIES_DIR, filename)
            if not os.path.isfile(filepath):
                continue
            mtime = datetime.fromtimestamp(os.path.getmtime(filepath))
            if mtime >= cutoff:
                try:
                    with open(filepath, "r", encoding="utf-8") as f:
                        content = f.read().strip()
                    if content:
                        entries_html += f'\n<div style="margin-bottom:24px;">{content}</div>'
                        count += 1
                except OSError:
                    pass
            else:
                old_files.append(filepath)
        if count == 0:
            return {"ok": True, "emails_combined": 0}
        subject = f"Fabio Telegram Weekly Digest - {datetime.now().strftime('%Y-%m-%d')}"
        combined_html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#1a1a2e;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<div style="max-width:600px;margin:0 auto;padding:20px;">
    <h1 style="font-size:22px;color:#e0e0e0;text-align:center;margin-bottom:4px;">Fabio Telegram Weekly Digest</h1>
    <p style="font-size:13px;color:#a0a0b0;text-align:center;margin-bottom:24px;">{datetime.now().strftime('%Y-%m-%d')} — {count} daily digests combined</p>
    {entries_html}
    <p style="font-size:11px;color:#a0a0b0;text-align:center;margin-top:24px;">Generated by MyHub Telegram Digest</p>
</div>
</body>
</html>"""
        email_result = send_email(subject, combined_html, config)
        for fp in old_files:
            try:
                os.remove(fp)
            except OSError:
                pass
        if email_result.get("ok"):
            return {"ok": True, "emails_combined": count}
        else:
            return {"ok": False, "error": email_result.get("error", "unknown")}
    except Exception as e:
        return {"error": str(e)}


def init_scheduler():
    _ensure_dirs()
    config = load_config()
    jobs_config = [
        {
            "id": "telegram_digest_daily",
            "func": run_digest_job,
            "cron": config.get("digest_cron", "0 8 * * *"),
            "name": "Telegram Digest Daily",
            "app": "telegram_digest",
        },
        {
            "id": "telegram_digest_weekly",
            "func": run_weekly_digest,
            "cron": config.get("weekly_digest_cron", "0 9 * * 1"),
            "name": "Telegram Digest Weekly",
            "app": "telegram_digest",
        },
        {
            "id": "telegram_files_check",
            "func": run_files_job,
            "cron": config.get("files_cron", "0 */6 * * *"),
            "name": "Telegram Files Check",
            "app": "telegram_files",
        },
    ]
    with _lock:
        for jc in jobs_config:
            enabled = config.get(f"{jc['id']}_enabled", True)
            _jobs[jc["id"]] = {
                "name": jc["name"],
                "app": jc["app"],
                "enabled": enabled,
                "total_runs": 0,
                "last_run": None,
                "last_result": None,
            }
            parts = jc["cron"].split()
            if len(parts) == 5:
                trigger = CronTrigger(
                    minute=parts[0],
                    hour=parts[1],
                    day=parts[2],
                    month=parts[3],
                    day_of_week=parts[4],
                )
                job = scheduler.add_job(
                    _run_job,
                    trigger=trigger,
                    args=[jc["id"], jc["func"], config],
                    id=jc["id"],
                    name=jc["name"],
                    replace_existing=True,
                    misfire_grace_time=3600,
                )
                if not enabled:
                    job.pause()
    scheduler.start()


def update_job_cron(job_id: str, cron_expression: str):
    config = load_config()
    with _lock:
        if job_id not in _jobs:
            raise ValueError(f"Unknown job_id: {job_id}")
        parts = cron_expression.split()
        if len(parts) != 5:
            raise ValueError("Cron expression must have 5 fields: minute hour day month day_of_week")
        trigger = CronTrigger(
            minute=parts[0],
            hour=parts[1],
            day=parts[2],
            month=parts[3],
            day_of_week=parts[4],
        )
        func_map = {
            "telegram_digest_daily": run_digest_job,
            "telegram_digest_weekly": run_weekly_digest,
            "telegram_files_check": run_files_job,
        }
        func = func_map[job_id]
        scheduler.reschedule_job(job_id, trigger=trigger)
        job = scheduler.get_job(job_id)
        if job:
            job.args = [job_id, func, config]


def enable_job(job_id: str):
    with _lock:
        if job_id not in _jobs:
            raise ValueError(f"Unknown job_id: {job_id}")
        job = scheduler.get_job(job_id)
        if job:
            job.resume()
        _jobs[job_id]["enabled"] = True


def disable_job(job_id: str):
    with _lock:
        if job_id not in _jobs:
            raise ValueError(f"Unknown job_id: {job_id}")
        job = scheduler.get_job(job_id)
        if job:
            job.pause()
        _jobs[job_id]["enabled"] = False


def get_all_jobs() -> list[dict]:
    result = []
    with _lock:
        for job_id, info in _jobs.items():
            job = scheduler.get_job(job_id)
            next_run = None
            if job and job.next_run_time:
                next_run = job.next_run_time.isoformat()
            result.append({
                "job_id": job_id,
                "name": info["name"],
                "app": info["app"],
                "enabled": info["enabled"],
                "total_runs": info["total_runs"],
                "last_run": info["last_run"],
                "last_result": info["last_result"],
                "next_run": next_run,
            })
    return result


def get_job_history(job_id: str) -> list[dict]:
    history = _load_history()
    return history.get(job_id, [])


def manual_run(job_id: str):
    with _lock:
        if job_id not in _jobs:
            raise ValueError(f"Unknown job_id: {job_id}")
        config = load_config()
        func_map = {
            "telegram_digest_daily": run_digest_job,
            "telegram_digest_weekly": run_weekly_digest,
            "telegram_files_check": run_files_job,
        }
        func = func_map[job_id]
    t = threading.Thread(target=_run_job, args=[job_id, func, config], daemon=True)
    t.start()
